#!/bin/bash

# ============================================================================
# Credentials Export Script
# ============================================================================
# This script exports all service credentials to a file for developers
# 
# Usage: 
#   ./get-credentials.sh                    # Output to terminal
#   ./get-credentials.sh > credentials.txt  # Save to file
# ============================================================================

set -e

echo "============================================================================"
echo "  AWS INFRASTRUCTURE CREDENTIALS"
echo "  Generated: $(date)"
echo "============================================================================"
echo ""

# Check if terraform is available
if ! command -v terraform &> /dev/null; then
    echo "ERROR: Terraform is not installed"
    exit 1
fi

# Check if terraform has been applied
if [ ! -f "terraform.tfstate" ] && [ ! -f ".terraform/terraform.tfstate" ]; then
    echo "ERROR: Terraform state not found. Run 'terraform apply' first."
    exit 1
fi

echo "============================================================================"
echo "  1. POSTGRESQL (RDS via RDS Proxy)"
echo "============================================================================"
echo ""
echo "Connection Details:"
echo "  Host:     $(terraform output -raw rds_proxy_endpoint 2>/dev/null || echo 'N/A')"
echo "  Port:     $(terraform output -raw rds_port 2>/dev/null || echo '5432')"
echo "  Database: $(terraform output -raw rds_database_name 2>/dev/null || echo 'N/A')"
echo "  Username: $(terraform output -raw rds_master_username 2>/dev/null || echo 'N/A')"
echo "  Password: $(terraform output -raw rds_password 2>/dev/null || echo 'N/A')"
echo ""
echo "Connection String:"
echo "  $(terraform output -raw rds_connection_string 2>/dev/null || echo 'N/A')"
echo ""
echo "Direct RDS Endpoint (without proxy):"
echo "  $(terraform output -raw rds_endpoint 2>/dev/null || echo 'N/A')"
echo ""
echo "Python (psycopg2):"
echo "  import psycopg2"
echo "  conn = psycopg2.connect("
echo "      host='$(terraform output -raw rds_proxy_endpoint 2>/dev/null || echo 'HOST')',"
echo "      port=$(terraform output -raw rds_port 2>/dev/null || echo '5432'),"
echo "      database='$(terraform output -raw rds_database_name 2>/dev/null || echo 'DATABASE')',"
echo "      user='$(terraform output -raw rds_master_username 2>/dev/null || echo 'USER')',"
echo "      password='$(terraform output -raw rds_password 2>/dev/null || echo 'PASSWORD')'"
echo "  )"
echo ""
echo "Node.js (pg):"
echo "  const { Pool } = require('pg');"
echo "  const pool = new Pool({"
echo "    host: '$(terraform output -raw rds_proxy_endpoint 2>/dev/null || echo 'HOST')',"
echo "    port: $(terraform output -raw rds_port 2>/dev/null || echo '5432'),"
echo "    database: '$(terraform output -raw rds_database_name 2>/dev/null || echo 'DATABASE')',"
echo "    user: '$(terraform output -raw rds_master_username 2>/dev/null || echo 'USER')',"
echo "    password: '$(terraform output -raw rds_password 2>/dev/null || echo 'PASSWORD')'"
echo "  });"
echo ""
echo "Environment Variables:"
echo "  export DB_HOST=$(terraform output -raw rds_proxy_endpoint 2>/dev/null || echo 'HOST')"
echo "  export DB_PORT=$(terraform output -raw rds_port 2>/dev/null || echo '5432')"
echo "  export DB_NAME=$(terraform output -raw rds_database_name 2>/dev/null || echo 'DATABASE')"
echo "  export DB_USER=$(terraform output -raw rds_master_username 2>/dev/null || echo 'USER')"
echo "  export DB_PASSWORD=$(terraform output -raw rds_password 2>/dev/null || echo 'PASSWORD')"
echo ""

echo "============================================================================"
echo "  2. REDIS (ElastiCache)"
echo "============================================================================"
echo ""
echo "Connection Details:"
echo "  Host:     $(terraform output -raw redis_endpoint 2>/dev/null || echo 'N/A')"
echo "  Port:     $(terraform output -raw redis_port 2>/dev/null || echo '6379')"
echo ""
echo "Connection String:"
echo "  $(terraform output -raw redis_connection_string 2>/dev/null || echo 'N/A')"
echo ""
echo "Python (redis-py):"
echo "  import redis"
echo "  r = redis.Redis("
echo "      host='$(terraform output -raw redis_endpoint 2>/dev/null || echo 'HOST')',"
echo "      port=$(terraform output -raw redis_port 2>/dev/null || echo '6379'),"
echo "      decode_responses=True"
echo "  )"
echo ""
echo "Node.js (ioredis):"
echo "  const Redis = require('ioredis');"
echo "  const redis = new Redis({"
echo "    host: '$(terraform output -raw redis_endpoint 2>/dev/null || echo 'HOST')',"
echo "    port: $(terraform output -raw redis_port 2>/dev/null || echo '6379')"
echo "  });"
echo ""
echo "Environment Variables:"
echo "  export REDIS_HOST=$(terraform output -raw redis_endpoint 2>/dev/null || echo 'HOST')"
echo "  export REDIS_PORT=$(terraform output -raw redis_port 2>/dev/null || echo '6379')"
echo ""

echo "============================================================================"
echo "  3. RABBITMQ (Amazon MQ)"
echo "============================================================================"
echo ""
echo "Connection Details:"
echo "  Endpoint:      $(terraform output -raw rabbitmq_endpoint 2>/dev/null || echo 'N/A')"
echo "  Console URL:   $(terraform output -raw rabbitmq_console_url 2>/dev/null || echo 'N/A')"
echo "  Username:      $(terraform output -raw rabbitmq_admin_username 2>/dev/null || echo 'N/A')"
echo "  Password:      $(terraform output -raw rabbitmq_admin_password 2>/dev/null || echo 'N/A')"
echo ""
echo "AMQP Connection String:"
echo "  $(terraform output -raw rabbitmq_amqp_connection_string 2>/dev/null || echo 'N/A')"
echo ""
echo "Python (pika):"
echo "  import pika"
echo "  credentials = pika.PlainCredentials("
echo "      '$(terraform output -raw rabbitmq_admin_username 2>/dev/null || echo 'USER')',"
echo "      '$(terraform output -raw rabbitmq_admin_password 2>/dev/null || echo 'PASSWORD')'"
echo "  )"
echo "  parameters = pika.ConnectionParameters("
echo "      host='$(terraform output -raw rabbitmq_endpoint 2>/dev/null || echo 'HOST' | cut -d: -f1)',"
echo "      port=5671,"
echo "      credentials=credentials,"
echo "      ssl_options=pika.SSLOptions()"
echo "  )"
echo "  connection = pika.BlockingConnection(parameters)"
echo ""
echo "Node.js (amqplib):"
echo "  const amqp = require('amqplib');"
echo "  const connection = await amqp.connect("
echo "      '$(terraform output -raw rabbitmq_amqp_connection_string 2>/dev/null || echo 'N/A')'"
echo "  );"
echo ""
echo "Environment Variables:"
echo "  export RABBITMQ_HOST=$(terraform output -raw rabbitmq_endpoint 2>/dev/null || echo 'HOST' | cut -d: -f1)"
echo "  export RABBITMQ_PORT=5671"
echo "  export RABBITMQ_USER=$(terraform output -raw rabbitmq_admin_username 2>/dev/null || echo 'USER')"
echo "  export RABBITMQ_PASSWORD=$(terraform output -raw rabbitmq_admin_password 2>/dev/null || echo 'PASSWORD')"
echo ""

echo "============================================================================"
echo "  4. CLICKHOUSE"
echo "============================================================================"
echo ""
echo "Connection Details:"
echo "  Private IP:    $(terraform output -raw clickhouse_private_ip 2>/dev/null || echo 'N/A')"
echo "  HTTP Port:     $(terraform output -raw clickhouse_http_port 2>/dev/null || echo '8123')"
echo "  Native Port:   $(terraform output -raw clickhouse_native_port 2>/dev/null || echo '9000')"
echo ""
echo "HTTP URL:"
echo "  $(terraform output -raw clickhouse_connection_string 2>/dev/null || echo 'N/A')"
echo ""
echo "Python (clickhouse-driver):"
echo "  from clickhouse_driver import Client"
echo "  client = Client("
echo "      host='$(terraform output -raw clickhouse_private_ip 2>/dev/null || echo 'HOST')',"
echo "      port=$(terraform output -raw clickhouse_native_port 2>/dev/null || echo '9000')"
echo "  )"
echo ""
echo "HTTP API (curl):"
echo "  curl 'http://$(terraform output -raw clickhouse_private_ip 2>/dev/null || echo 'HOST'):8123/' --data 'SELECT version()'"
echo ""
echo "Environment Variables:"
echo "  export CLICKHOUSE_HOST=$(terraform output -raw clickhouse_private_ip 2>/dev/null || echo 'HOST')"
echo "  export CLICKHOUSE_PORT=9000"
echo "  export CLICKHOUSE_HTTP_PORT=8123"
echo ""

echo "============================================================================"
echo "  5. S3 BUCKET"
echo "============================================================================"
echo ""
echo "Bucket Name: $(terraform output -raw s3_bucket_name 2>/dev/null || echo 'N/A')"
echo "Bucket ARN:  $(terraform output -raw s3_bucket_arn 2>/dev/null || echo 'N/A')"
echo "Region:      $(terraform output -raw s3_bucket_region 2>/dev/null || echo 'N/A')"
echo ""
echo "Python (boto3):"
echo "  import boto3"
echo "  s3 = boto3.client('s3')"
echo "  s3.upload_file('local-file.txt', '$(terraform output -raw s3_bucket_name 2>/dev/null || echo 'BUCKET')', 'remote-file.txt')"
echo ""
echo "AWS CLI:"
echo "  aws s3 ls s3://$(terraform output -raw s3_bucket_name 2>/dev/null || echo 'BUCKET')/"
echo "  aws s3 cp file.txt s3://$(terraform output -raw s3_bucket_name 2>/dev/null || echo 'BUCKET')/"
echo ""

echo "============================================================================"
echo "  6. ECR (CONTAINER REGISTRY)"
echo "============================================================================"
echo ""
echo "Login Command:"
echo "  $(terraform output -raw ecr_login_command 2>/dev/null || echo 'N/A')"
echo ""
echo "Repositories:"
terraform output -json ecr_repository_urls 2>/dev/null | jq -r 'to_entries[] | "  \(.key): \(.value)"' 2>/dev/null || echo "  N/A"
echo ""

echo "============================================================================"
echo "  7. EKS CLUSTER"
echo "============================================================================"
echo ""
echo "Cluster Name: $(terraform output -raw eks_cluster_name 2>/dev/null || echo 'N/A')"
echo "Endpoint:     $(terraform output -raw eks_cluster_endpoint 2>/dev/null || echo 'N/A')"
echo ""
echo "Configure kubectl:"
echo "  $(terraform output -raw eks_configure_kubectl 2>/dev/null || echo 'N/A')"
echo ""

echo "============================================================================"
echo "  8. LOAD BALANCER"
echo "============================================================================"
echo ""
echo "ALB DNS:      $(terraform output -raw alb_dns_name 2>/dev/null || echo 'N/A')"
echo "Jenkins URL:  $(terraform output -raw jenkins_url 2>/dev/null || echo 'N/A')"
echo "API URL:      $(terraform output -raw api_url 2>/dev/null || echo 'N/A')"
echo ""

echo "============================================================================"
echo "  9. EC2 INSTANCE (ClickHouse + Jenkins)"
echo "============================================================================"
echo ""
echo "Instance ID:  $(terraform output -raw clickhouse_instance_id 2>/dev/null || echo 'N/A')"
echo "Private IP:   $(terraform output -raw clickhouse_private_ip 2>/dev/null || echo 'N/A')"
echo ""
echo "Connect via SSM:"
echo "  $(terraform output -raw ec2_ssm_connect_command 2>/dev/null || echo 'N/A')"
echo ""

echo "============================================================================"
echo "  10. SECRETS MANAGER ARNs"
echo "============================================================================"
echo ""
echo "RDS Secret:      $(terraform output -raw rds_secret_arn 2>/dev/null || echo 'N/A')"
echo "RabbitMQ Secret: $(terraform output -raw rabbitmq_secret_arn 2>/dev/null || echo 'N/A')"
echo ""

echo "============================================================================"
echo "  QUICK REFERENCE - COPY-PASTE FOR .env FILE"
echo "============================================================================"
echo ""
echo "# PostgreSQL"
echo "DB_HOST=$(terraform output -raw rds_proxy_endpoint 2>/dev/null || echo 'HOST')"
echo "DB_PORT=$(terraform output -raw rds_port 2>/dev/null || echo '5432')"
echo "DB_NAME=$(terraform output -raw rds_database_name 2>/dev/null || echo 'DATABASE')"
echo "DB_USER=$(terraform output -raw rds_master_username 2>/dev/null || echo 'USER')"
echo "DB_PASSWORD=$(terraform output -raw rds_password 2>/dev/null || echo 'PASSWORD')"
echo ""
echo "# Redis"
echo "REDIS_HOST=$(terraform output -raw redis_endpoint 2>/dev/null || echo 'HOST')"
echo "REDIS_PORT=$(terraform output -raw redis_port 2>/dev/null || echo '6379')"
echo ""
echo "# RabbitMQ"
echo "RABBITMQ_HOST=$(terraform output -raw rabbitmq_endpoint 2>/dev/null || echo 'HOST' | cut -d: -f1)"
echo "RABBITMQ_PORT=5671"
echo "RABBITMQ_USER=$(terraform output -raw rabbitmq_admin_username 2>/dev/null || echo 'USER')"
echo "RABBITMQ_PASSWORD=$(terraform output -raw rabbitmq_admin_password 2>/dev/null || echo 'PASSWORD')"
echo "RABBITMQ_URL=$(terraform output -raw rabbitmq_amqp_connection_string 2>/dev/null || echo 'N/A')"
echo ""
echo "# ClickHouse"
echo "CLICKHOUSE_HOST=$(terraform output -raw clickhouse_private_ip 2>/dev/null || echo 'HOST')"
echo "CLICKHOUSE_PORT=9000"
echo "CLICKHOUSE_HTTP_PORT=8123"
echo ""
echo "# S3"
echo "S3_BUCKET=$(terraform output -raw s3_bucket_name 2>/dev/null || echo 'BUCKET')"
echo ""
echo "============================================================================"
echo ""
echo "⚠️  SECURITY WARNING:"
echo "    - These credentials are SENSITIVE"
echo "    - Do NOT commit to Git"
echo "    - Store securely (use .env file with .gitignore)"
echo "    - Rotate passwords regularly"
echo ""
echo "============================================================================"
echo "  Script completed at: $(date)"
echo "============================================================================"

